---
- name: Install driver repo
  ansible.builtin.apt:
    deb: "{{ download_url }}"
  when: not gpu_install_dry_run

- name: Find GPG key
  ansible.builtin.find:
    paths: /var/nvidia-driver-local-repo-ubuntu{{ ansible_distribution_version | replace('.', '') }}-{{ gpu_install_driver_version }}
    patterns: "nvidia-driver-*-keyring.gpg"
    file_type: file
  when: not gpu_install_dry_run
  register: keys

- name: Copy GPG key to needed location
  ansible.builtin.copy:
    remote_src: true
    src: "{{ item.path }}"
    dest: /usr/share/keyrings/
    mode: "0644"
    owner: root
    group: root
  when: not gpu_install_dry_run
  with_items: "{{ keys.files }}"

- name: Install Drivers
  ansible.builtin.apt:
    update_cache: true
    name:
      - cuda-drivers
  notify:
    - Reboot system
  when: not gpu_install_dry_run

- name: Install CUDA
  when: not gpu_install_dry_run and gpu_install_library
  block:
    - name: Install CUDA Keyring
      ansible.builtin.apt:
        deb: "{{ lookup('ansible.builtin.template', 'nvidia/cuda_deb_repo.j2', template_vars={'distro': 'ubuntu'}) }}"

    - name: Install CUDA toolkit
      ansible.builtin.apt:
        pkg:
          - nvidia-cuda-toolkit
