---
- name: Fail on unsupported distribution
  ansible.builtin.fail:
    msg: "Unsupported distribution {{ ansible_distribution }}"
  when: (ansible_distribution | lower) not in ["redhat", "ubuntu", "fedora", "amazon"]

- name: Prepare system facts
  ansible.builtin.include_tasks:
    file: "{{ gpu_install_vendor }}/pre_download/{{ ansible_distribution | lower }}.yml"

- name: Set defaults
  block:
    - name: Set default driver version
      ansible.builtin.set_fact:
        gpu_install_driver_version: "{{ gpu_install_driver_version | default(driver_version_default.nvidia) }}"
    - name: Set default library version
      ansible.builtin.set_fact:
        gpu_install_library_version: "{{ gpu_install_library_version | default(library_version_default.nvidia) }}"

- name: Verify driver version exists
  block:
    - name: Check Nvidia URL
      ansible.builtin.uri:
        url: "{{ download_url }}"
        method: HEAD # Using HEAD to prevent a full download
      no_log: true # Hide the ugly output
  rescue: # Display the nicer output
    - name: Fail if driver version not found
      ansible.builtin.fail:
        msg: "Could not find driver version {{ gpu_install_driver_version }} at {{ download_url }}"

- name: Configure System
  ansible.builtin.include_tasks:
    file: "{{ gpu_install_vendor }}/install/{{ ansible_distribution | lower }}.yml"
